FROM python:3.12-slim

WORKDIR /extract

COPY ./spells/extract /extract
COPY ./requirements.txt /extract/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
