FROM python:3.12

WORKDIR /transform

COPY ./spells/transform /transform
COPY ./requirements.txt /transform/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
